### ISSUE TITLE
Support for ZUGFeRD 1.0 CrossIndustryDocument

### ISSUE THREAD

**Issue by mikelkra** [horstoeko/zugferd#115]
Hi, and thank you for developing this package!

Questions:

1. Can you add support for ZUGFeRD 1.0 CrossIndustryDocument?
    Currently, the package supports only CrossIndustryInvoice in ZUGFeRD 2.0.
` xpath('/rsm:CrossIndustryInvoice/rsm:ExchangedDocumentContext/ram:GuidelineSpecifiedDocumentContextParameter/ram:ID');
`
    The difference between both versions is minimal, with slight differences in the invoice XML structure.
    Our Problem:
    We need to process multiple versions of documents through our application, and supporting ZUGFeRD 1.0 would be beneficial for handling legacy documents.
    Here is an example file [RG-110912 1.pdf](https://github.com/user-attachments/files/16991363/RG-110912.1.pdf)

2. When will you add support for secured pdf files?
    It would be good to get rid of the "Secured pdf file are currently not supported" message :)

Thank You

**Comment by horstoeko** [comment]
Hi @mikelkra,

thank you for your question.

> Can you add support for ZUGFeRD 1.0 CrossIndustryDocument?

No. This will not be implemented. 

ZUGFeRD 1.0 is the first version of a hybrid e-invoice format that combines PDF and XML data. Although it can still be used technically, it is no longer being actively developed and is no longer supported by current guidelines.

From November 27, 2020, public clients must be able to receive and process invoices in a machine-readable format in accordance with EU standard EN 16931. ZUGFeRD 2.1.1 and higher (e.g. ZUGFeRD 2.2 and ZUGFeRD 2.2.1) comply with this standard, while ZUGFeRD 1.0 is not compliant.

It is therefore advisable to switch to ZUGFeRD 2.x or the Peppol format in order to meet legal and technical requirements and ensure compatibility.

> When will you add support for secured pdf files?
> It would be good to get rid of the "Secured pdf file are currently not supported" message :)

This message does not come from **my** library. I use the [smalot/pdfparser](https://github.com/smalot/pdfparser) library to read the PDF files. The library smalot/pdfparser offers the possibility to skip this message. However, I am not sure whether the PDF can then still be read correctly. I have not yet checked this myself. I will see if I can implement the override when I get the chance.

I hope that this answers your questions sufficiently.

Kind regards
