### ISSUE TITLE
How change AFRelationship From "Data" to "Alternative"

### ISSUE THREAD

**Issue by mwolfrath-ok** [horstoeko/zugferd#147]
**How change AFRelationship**
My Datev Import fails, because my ZUGFerd-file contains "/AFRelationship /Data". 
But Importer needs "/AFRelationship /Alternative"

**Screenshot Output Zugferd-PDF**
![image](https://github.com/user-attachments/assets/f6b53541-811d-4dbc-8a25-fd4ff8e127a5)

**Code to reproduce**
$xmlData = $this->zugferdXRechnung->getXmlContent(); // ZugferdXmlDocBuilder()->getContent();
$pdfData = $pdf->ezOutput(); // PDF-Content from ERP			
$zugferdPdfMerger = new ZugferdDocumentPdfMerger($xmlData, $pdfData);			
$zugferdPdfMerger->generateDocument()->saveDocument($outputFileName);			

**Additional information:**
OS: Windows
OS-Version Windows 10
PHP-Version PHP 8.2

**Comment by horstoeko** [comment]
Hi @mwolfrath-ok,

at the moment I have not provided a way to change this. However, I will think about how I can make this configurable

Kind regards

**Comment by mwolfrath-ok** [comment]
Thank you for answer

ich think, this will be a great "Deal", because DATEV is a great german Portal for Steuerberater (tax advisor)

I look forward to a positive response 
and kind Regards

**Comment by horstoeko** [comment]
Hi @mwolfrath-ok,

I've added a method called "setAttachmentRelationshipType" to the classes _ZugferdDocumentPdfBuilderAbstract_-, _ZugferdDocumentPdfBuilder_- and _ZugferdDocumentPdfMerger_. The method takes two values: "Data" and "Alternative". If the value doesn't fit, "Data" is assumed.

This is coming with the next release

Kind regards

**Comment by winnyschuster** [comment]
@horstoeko first thank you for this great piece of software! this is what the newest spec says about *AF relatinship*:
> In Deutschland ist aus rechtlichen Gründen nur der Wert "Alternative" zulässig; das bedeutet, dass alle Information, die im menschlesbaren Teil gegenwärtig sind, auch im XML-Teil enthalten sein müssen, selbst wenn sie in nicht strukturiertem Text vorkommen („identisches Mehrstück“).

it is probably better to have it the other way around, as `Data` or `Source` are only allowed in France. For Germany it has always to be **Alternative**

**Comment by horstoeko** [comment]
Hi @winnyschuster,
Hi @mwolfrath-ok,

What madness. I'm not surprised that everyone is totally unsettled about electronic invoicing when it comes to such small-scale issues. For reasons of downward compatibility, I would like to leave the setting at “Data”. Is there anything against this from your point of view?

> In Deutschland ist aus rechtlichen Gründen nur der Wert "Alternative" zulässig; das bedeutet, dass alle Information, die im menschlesbaren Teil gegenwärtig sind, auch im XML-Teil enthalten sein müssen, selbst wenn sie in nicht strukturiertem Text vorkommen („identisches Mehrstück“).

Thank you for the information @winnyschuster . Where did you get this information from?

Kind regards

**Comment by horstoeko** [comment]
Hi @winnyschuster and @mwolfrath-ok,

Vielleicht könnte das eine Lösung sein, die alle Seiten zufrieden stellt? (See PR #149)

Kind regards

**Comment by winnyschuster** [comment]
@horstoeko i can't go back in history before version 2.2 but i'm pretty sure that **Alternative** was the only value ever allowed in Germany. I do not consider this a small-scale issue i(n Germany!)since any PDF having different AF relationship setting will be treated as invalid. I'm not even sure if any of the many validation tools out there check for this case but i know german authorities will:

Having said this, providing a setting as you already did schould be good for now, heavy usage of Zugferd software will only start in January. Users of your software are developers anyway and these should know what they are doing.

you can obtain a complete official bundle of the newest 2.3 specification and former version 2.2 at no cost from [here](https://www.ferd-net.de/standards/zugferd-2.3/zugferd-2.3.html). There a lots of infos in the package including newest files to validate the xml with for all profiles

since XRECHNUNG has its own specification not developed by the ZugFerd team, there is another files bundle avalable at [this site](https://xeinkauf.de/xrechnung/versionen-und-bundles/), also at no cost. the newest version is 3.0.2

last but not least there are copies of the en16931 semantic model available at no cost from [dinmedia](https://www.dinmedia.de/de/erweiterte-suche/1052992!search?alx.searchType=complex&alx.search.autoSuggest=false&searchAreaId=1&query=en16931-1&facets%5B1053000%5D=&hitsPerPage=10). the first link there is what you want, available after registration, in german language. The more interesting parts (at least for programmers) en-16931-3 to -5 cost lot of money but these points are all covered by the first two links of this post.

took me a while to gather all this information when i started interest in e-invoicing, so i'm happy to share them. Hope it helps and thanks again for this project

**Comment by winnyschuster** [comment]
> Hi @winnyschuster and @mwolfrath-ok,
> 
> Perhaps this could be a solution that satisfies all sides? (See PR #149 )

i think yes, it does. Absolutely incredible response time, btw

**Comment by horstoeko** [comment]
Hi @winnyschuster 

> took me a while to gather all this information when i started interest in e-invoicing, so i'm happy to share them. Hope it helps and thanks again for this project

I am happy about everyone who appreciates the work for this project. It's also good to know that there are more committed people out there who are keen to get to grips with this issue.Maybe we can stay in touch @winnyschuster.

>  Absolutely incredible response time, btw

I have a day off... Actually reserved for private things... But what the heck :-)

Kind regards.

**Comment by winnyschuster** [comment]
just had a chance to test 1.0.72 and it works as expected. The new setting is easy to use and does exactly what it is for. 

unfortunately i was right in guessing that validators do not check for the metada, especially tested a wrong AFRelationship.setting. I've used mustang-cli for that purpose which itself is relying on veraPDF

btw, are there plans to updating validation xsd files to newest ones? Or even just adding them so one could choose between 2.2 and 2.3

> Maybe we can stay in touch ...

for sure :-)

**Comment by horstoeko** [comment]
Hi @winnyschuster,

> btw, are there plans to updating validation xsd files to newest ones? Or even just adding them so one could choose between 2.2 and 2.3

Everything here should be version 2.3... :-) See [Release 1.0.62](https://github.com/horstoeko/zugferd/releases/tag/v1.0.62). If you find anything that seems to be incompatible with 2.3, please open a separate issue.

Kind regards
