### ISSUE TITLE
[QUESTION] Seller electronic address, Buyer electronic address

### ISSUE THREAD

**Issue by danielbarenkamp** [horstoeko/zugferd#160]
**Your question**
First thanks for all that work! I really appreciate it.

Now I get these errors:

**Seller electronic address MUST be provided**
**Buyer electronic address MUST be provided**

```
val-sch.2.2 | PEPPOL-EN16931-R020 | information | Seller electronic address MUST be provided
-- | -- | -- | --
Pfad: /rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction[1]/ram:ApplicableHeaderTradeAgreement[1]/ram:SellerTradeParty[1]
val-sch.2.3 | PEPPOL-EN16931-R010 | information | Buyer electronic address MUST be provided
Pfad: /rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction[1]/ram:ApplicableHeaderTradeAgreement[1]/ram:BuyerTradeParty[1]
```

Do you have any **example** how to use this class: https://github.com/horstoeko/zugferd/blob/74bd98c0fa883048f80563e08042556f8f0294ce/src/codelists/ZugferdElectronicAddressScheme.php#L23

**Comment by horstoeko** [comment]
Hi @danielbarenkamp,

> First thanks for all that work! I really appreciate it.

Thank you very much. I am always pleased when people have a word of thanks for my work.

> Now I get these errors:
>
> **Seller electronic address MUST be provided** **Buyer electronic address MUST be provided**

Nothing easier than that... :-) The ``ZugferdDocumentBuilder`` has the following two methods:

* setDocumentSellerCommunication _(for the seller party)
* setDocumentBuyerCommunication _(for the buyer party)

The first parameter takes values from the mentioned class ``ZugferdElectronicAddressScheme``. The second parameter contains the value matching the specified scheme. To specify an email address, you could write the following (for example):

```php
$document = ZugferdDocumentBuilder::CreateNew(ZugferdProfiles::PROFILE_EN16931);
$document->setDocumentSellerCommunication(ZugferdElectronicAddressScheme::UNECE3155_EM, 'mail@nowhere.all');
```

I hope this helps you. If not, please ask your question again in more detail, otherwise I would ask you to close the topic yourself.

Many thanks and best regards

**Comment by danielbarenkamp** [comment]
Awesome! Thanks so much!

Now my only issue is this last warning:


[BR-DE-21] Das Element "Specification identifier" (BT-24) soll syntaktisch der Kennung des Standards XRechnung entsprechen.
--
Pfad: /rsm:CrossIndustryInvoice/rsm:ExchangedDocumentContext[1]

**Comment by horstoeko** [comment]
Hi @danielbarenkamp,

fine. Which profile you use to create the XML via ZugferdDocumentBuilder?

I assume you are using an older version of XRechnung. The current version is version 3. Maybe you can at least post an excerpt from the XML, as my crystal ball is under repair... :-)

Kind regards.

**Comment by danielbarenkamp** [comment]
I use the one from your examples: 

$document = ZugferdDocumentBuilder::CreateNew(ZugferdProfiles::PROFILE_EN16931);

**Comment by horstoeko** [comment]
Hi @danielbarenkamp,

PROFILE_EN16931 is not XRECHNUNG. See the following table

| Profile | ContextParameter (BT-24)
| :------- | :----------------------------
| PROFILE_EN16931  | urn:cen.eu:en16931:2017
| PROFILE_XRECHNUNG_3 | urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0

Try using the following:

```php
$document = ZugferdDocumentBuilder::CreateNew(ZugferdProfiles::PROFILE_XRECHNUNG_3);
```

Kind regards

**Comment by danielbarenkamp** [comment]
Thank you very much!
