### ISSUE TITLE
[BUG]Warning: Undefined array key 0 on getDocumentInvoicerContact()

### ISSUE THREAD

**Issue by Odido** [horstoeko/zugferd#210]
**Describe the bug**
I try to run getDocumentInvoicerContact() on your invoice-2.xml that can be found on Github. When the code tries to execute $contact = $contacs[$this->documentInvoiceContactPointer]; from within getDocumentInvoicerContact() I get the undefinded array key. I tried different xmls. It's always the same.

**To Reproduce**
execute
$document = ZugferdDocumentReader::readAndGuessFromFile("incoming/invoice-2.xml");
$test = $document->getDocumentInvoicerContact($contactPersonName, $contactDepartmentName, $contactPhoneNo, $contactFaxNo, $contactEmailAddress);

The command $contacts = $this->getObjectHelper()->..., line 1 in ZugferdDocumentReader/getDocumentInvoicerContact() returns an empty array so the second line produces the undefined array key.

**Expected behavior**
I expect null to be returned, if there are no data. Otherwise I expect the corresponding values.

**Sample Code
see above

**Screenshot
![horstoeko](https://github.com/user-attachments/assets/44661638-8ce0-4125-a37b-d621d88c8e8b)

**Additional information:**
 - OS: DDEV with Ubuntu
 - OS-Version 24.04.1 LTS
 - PHP-Version 8.2

**Additional context**

**Comment by horstoeko** [comment]
Hi  @Odido,

you did not read the docs and had no look to the examples - that is a great pity... :-(

Please use the following methods before using the getContact-Method

* [firstDocumentInvoiceeContact](https://github.com/horstoeko/zugferd/wiki/Class-ZugferdDocumentReader#firstdocumentinvoiceecontact)
* [nextDocumentInvoiceeContact](https://github.com/horstoeko/zugferd/wiki/Class-ZugferdDocumentReader#nextdocumentinvoiceecontact)

## Sample code

```php
if ($document->firstDocumentInvoiceeContact()) {
  do {
    $document->getDocumentInvoicerContact($contactPersonName, $contactDepartmentName, $contactPhoneNo, $contactFaxNo, $contactEmailAddress);
  } while ($document->nextDocumentInvoiceeContact());
}
```

There is an [example](https://github.com/horstoeko/zugferd/blob/master/examples/En16931ReaderPdf.php) where the first/next methods are used.

I will close this this issue since this is no bug.

Kind regards
