### ISSUE TITLE
Dead link to GitHub page

### ISSUE THREAD

**Issue by danielmarschall** [horstoeko/zugferd#51]
At the GitHub page, there is a link to "[horstoeko.github.io/zugferd/](https://horstoeko.github.io/zugferd/)" which is dead.

Additionally, I want to ask if you are accepting donations (possible with SEPA Überweisung, not with PayPal).

**Comment by horstoeko** [comment]
Hi @danielmarschall,

Thanks for pointing out the non-existent GitHub page. 

> At the GitHub page, there is a link to "[horstoeko.github.io/zugferd/](https://horstoeko.github.io/zugferd/)" which is dead.

I had tried to start that once, but didn't get any further due to lack of time. I have removed the link until I find the time.
 
> Additionally, I want to ask if you are accepting donations (possible with SEPA Überweisung, not with PayPal).

I am still undecided about this. I am actually very happy to "sacrifice" my free time for this topic, as I also have a personal interest in it.

Best regards...
